# Projet : Vivaria
# Auteurs : Benjamin MICHALAK, Angel SANCHEZ, Augustin MINOT

"""
Tous les paramètres réglables du jeu.
"""

# Affichage
FPS = 60
VITESSE_SIMULATION_BASE = 1 # Agis comme valeur à réattribuer
VITESSE_SIMULATION = [1, 2, 5, 10] # Agis comme multiplicateur
CHRONO_MS_BASE = 208
CHRONO_MS = 208
CHRONO_GRAPH_BASE = 208
CHRONO_GRAPH = 208
CHRONO_GRAPH_UPDATE_BASE = 1000
CHRONO_GRAPH_UPDATE = 1000
TAILLE_SPRITE = (50, 50)

# Paramètres d'affichage de la fenêtre principale du jeu
LARGEUR = 800
HAUTEUR = 600
TAILLE_FONT = 20

# Paramètres de simulation
NOMBRE_INITIAL_PLANTES = 20
NOMBRE_INITIAL_HERBIVORES = 10
NOMBRE_INITIAL_CARNIVORES = 5

# Paramètres de comportement des organismes
AGE_BASE = 1
CROISSANCE_BASE = 0.05
CROISSANCE = 0.05
DELAIS_SPAWN_PLANTES_BASE = 300
DELAIS_SPAWN_PLANTES = 300
DELAIS_SPAWN_HERBIVORES_BASE = 350
DELAIS_SPAWN_HERBIVORES = 350
DELAIS_SPAWN_CARNIVORES_BASE = 500
DELAIS_SPAWN_CARNIVORES = 500

# Energie
ENERGIE_MAX_HERBIVORE = 100
ENERGIE_MAX_CARNIVORE = 100
ENERGIE_RECHARGE = 40
# Coût d'énergie
COUT_ENERGY_HERBIVORE_BASE = 0.05
COUT_ENERGY_HERBIVORE = 0.05
COUT_ENERGY_CARNIVORE_BASE = 0.05
COUT_ENERGY_CARNIVORE = 0.05
MULT_COUT_ENERGY_DESERT = 1.2
# Vitesse
VITESSE_HERBIVORE_BASE = 1
VITESSE_HERBIVORE = 1
VITESSE_CARNIVORE_BASE = 1.1
VITESSE_CARNIVORE = 1.1
MULT_VITESSE_PLAINE = 1.0
MULT_VITESSE_FORET = 1.2
MULT_VITESSE_DESERT = 0.5
MULT_VITESSE_TOUNDRA = 0.8
# Rayon de vision
RAYON_VISION_HERBIVORE = 50
RAYON_VISION_CARNIVORE = 50

# Multiplicateurs environnementaux
# Biomes
MULT_BIOME_PLAINE = 1.0
MULT_BIOME_FORET = 1.2
MULT_BIOME_DESERT = 0.5
MULT_BIOME_TOUNDRA = 0.8
# Meteo
MULT_METEO_SOLEIL = 1.0
MULT_METEO_PLUIE = 1.5
MULT_METEO_ORAGE = 0.8
MULT_METEO_NEIGE = 0.5
# Saisons
MULT_SAISON_PRINTEMPS = 1.5
MULT_SAISON_ETE = 1.0
MULT_SAISON_AUTOMNE = 0.8
MULT_SAISON_HIVER = 0.5
